### ISSUE TITLE
使用出错

### ISSUE THREAD

**Issue by dubinhong** [ChinaSilence/spring-boot-starter-grpc#1]
我在我的controller层注入调用接口，然后一直报
![default](https://user-images.githubusercontent.com/33817575/41399038-d6b997ba-6feb-11e8-9adf-9eaef1f1b0ad.png)

这个错是什么原因
以下是我客户端配置以及代码：
![default](https://user-images.githubusercontent.com/33817575/41399180-35cf8e30-6fec-11e8-9964-97ca1373f371.png)
![default](https://user-images.githubusercontent.com/33817575/41399189-3ba7e1c2-6fec-11e8-939c-2f2bdd5aa6a8.png)
![default](https://user-images.githubusercontent.com/33817575/41399282-785a2d6e-6fec-11e8-9bdc-2c9196a258a8.png)
服务端配置；
server:
    port: 8007
spring:
    application:
        name: test
    grpc:
        enable: true
        port: 8008

**Comment by AnoyiX** [comment]
客户端要配置远程服务提供方的信息，示例：
```
spring:
  grpc:
    remote-servers:
      - server: user
        host: localhost
        port: 6565
```
