### ISSUE TITLE
Startup Client error

### ISSUE THREAD

**Issue by ghost** [ChinaSilence/spring-boot-starter-grpc#6]
我对着说明启动，但ipAddress似乎无法解析,启动的ipv6,需要在哪里关闭？
报错日志如下:

2019-01-29 17:17:40.975  WARN 21536 --- [ault-executor-0] i.g.i.ManagedChannelIm pl                 : [Channel<1>: (server:6565)] Failed to resolve name. status= Status{code=UNAVAILABLE, description=Unable to resolve host server, cause=java.l ang.RuntimeException: java.net.UnknownHostException: server                              at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:399)         at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResol ver.java:269)                                                                            at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225 )                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor. java:1149)                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor .java:624)                                                                               at java.lang.Thread.run(Thread.java:748)                                 Caused by: java.net.UnknownHostException: server                                         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)                    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)                at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:132 3)                                                                                       at java.net.InetAddress.getAllByName0(InetAddress.java:1276)                     at java.net.InetAddress.getAllByName(InetAddress.java:1192)                      at java.net.InetAddress.getAllByName(InetAddress.java:1126)                      at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(Dn sNameResolver.java:624)                                                                  at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:367)         ... 5 more                                                               }

**Comment by AnoyiX** [comment]
发下你的应用配置

**Comment by ghost** [comment]
client配置:
```
server:
  port: 8081

spring:
  grpc:
    remote-servers:
    - server: user
      host: server
      port: 6565
```

server配置:
```
server:
  port: 8080

spring:
  grpc:
    enable: true
    port: 6565
```
文件是从当前版本git clone 下载的,未作修改

**Comment by AnoyiX** [comment]
client 配置修改下:

```
server:
  port: 8081

spring:
  grpc:
    remote-servers:
    - server: user
      host: 127.0.0.1
      port: 6565
```
